-- The executable schema now lives in timestamped Supabase migrations.
-- Apply `supabase/migrations/202607160001_initial_backend.sql` with:
--   supabase db reset       (local)
--   supabase db push        (linked project)
--
-- Keeping this file as a pointer avoids schema drift between a hand-maintained
-- snapshot and the migration history.
