"""initial_ingestion_schema

Revision ID: 20260716_0001
Revises: 
Create Date: 2026-07-16 14:51:59.958827
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20260716_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('calendar_system', sa.String(length=30), nullable=False),
    sa.Column('official_domains', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions'))
    )
    op.create_table('record_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_record_ids', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_versions')),
    sa.UniqueConstraint('record_type', 'canonical_key', 'content_hash', name=op.f('uq_record_versions_record_type_canonical_key_content_hash')),
    sa.UniqueConstraint('record_type', 'canonical_key', 'version_number', name=op.f('uq_record_versions_record_type_canonical_key_version_number'))
    )
    op.create_index(op.f('ix_record_versions_canonical_key'), 'record_versions', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_record_versions_content_hash'), 'record_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_record_versions_record_type'), 'record_versions', ['record_type'], unique=False)
    op.create_index(op.f('ix_record_versions_superseded'), 'record_versions', ['superseded'], unique=False)
    op.create_table('admissions_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('applicant_type', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('timing', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_record_ids', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('unresolved_fields', sa.JSON(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_admissions_rules_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admissions_rules'))
    )
    op.create_index(op.f('ix_admissions_rules_applicant_type'), 'admissions_rules', ['applicant_type'], unique=False)
    op.create_index(op.f('ix_admissions_rules_campus'), 'admissions_rules', ['campus'], unique=False)
    op.create_index(op.f('ix_admissions_rules_confidence_tier'), 'admissions_rules', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_admissions_rules_content_hash'), 'admissions_rules', ['content_hash'], unique=False)
    op.create_index(op.f('ix_admissions_rules_institution_id'), 'admissions_rules', ['institution_id'], unique=False)
    op.create_index(op.f('ix_admissions_rules_review_status'), 'admissions_rules', ['review_status'], unique=False)
    op.create_index(op.f('ix_admissions_rules_rule_type'), 'admissions_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_admissions_rules_superseded'), 'admissions_rules', ['superseded'], unique=False)
    op.create_table('catalog_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.String(length=30), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_catalog_versions_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_versions'))
    )
    op.create_index(op.f('ix_catalog_versions_institution_id'), 'catalog_versions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_catalog_versions_superseded'), 'catalog_versions', ['superseded'], unique=False)
    op.create_table('conflict_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_ids', sa.JSON(), nullable=False),
    sa.Column('conflict_type', sa.String(length=100), nullable=False),
    sa.Column('differing_fields', sa.JSON(), nullable=False),
    sa.Column('source_authorities', sa.JSON(), nullable=False),
    sa.Column('effective_periods', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('suggested_review_action', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_conflict_records_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflict_records'))
    )
    op.create_index(op.f('ix_conflict_records_conflict_type'), 'conflict_records', ['conflict_type'], unique=False)
    op.create_index(op.f('ix_conflict_records_institution_id'), 'conflict_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_record_type'), 'conflict_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_conflict_records_status'), 'conflict_records', ['status'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('parser_versions', sa.JSON(), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('pages_skipped', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_crawl_jobs_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_jobs'))
    )
    op.create_index(op.f('ix_crawl_jobs_institution_id'), 'crawl_jobs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('exam_credit_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('exam_name', sa.Text(), nullable=False),
    sa.Column('score_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('score_max', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('awarded_courses', sa.JSON(), nullable=False),
    sa.Column('awarded_credit_values', sa.JSON(), nullable=False),
    sa.Column('general_education_designators', sa.JSON(), nullable=False),
    sa.Column('placement_effect', sa.Text(), nullable=True),
    sa.Column('duplicate_credit_rule', sa.Text(), nullable=True),
    sa.Column('native_speaker_rule', sa.Text(), nullable=True),
    sa.Column('major_specific_applicability', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_record_ids', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('unresolved_fields', sa.JSON(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_exam_credit_rules_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_credit_rules'))
    )
    op.create_index(op.f('ix_exam_credit_rules_confidence_tier'), 'exam_credit_rules', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_exam_credit_rules_content_hash'), 'exam_credit_rules', ['content_hash'], unique=False)
    op.create_index(op.f('ix_exam_credit_rules_exam_name'), 'exam_credit_rules', ['exam_name'], unique=False)
    op.create_index(op.f('ix_exam_credit_rules_exam_type'), 'exam_credit_rules', ['exam_type'], unique=False)
    op.create_index(op.f('ix_exam_credit_rules_institution_id'), 'exam_credit_rules', ['institution_id'], unique=False)
    op.create_index(op.f('ix_exam_credit_rules_review_status'), 'exam_credit_rules', ['review_status'], unique=False)
    op.create_index(op.f('ix_exam_credit_rules_superseded'), 'exam_credit_rules', ['superseded'], unique=False)
    op.create_table('source_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('policy_family', sa.String(length=50), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_source_pages_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_pages')),
    sa.UniqueConstraint('institution_id', 'canonical_url', name=op.f('uq_source_pages_institution_id_canonical_url'))
    )
    op.create_index(op.f('ix_source_pages_campus'), 'source_pages', ['campus'], unique=False)
    op.create_index(op.f('ix_source_pages_institution_id'), 'source_pages', ['institution_id'], unique=False)
    op.create_index(op.f('ix_source_pages_policy_family'), 'source_pages', ['policy_family'], unique=False)
    op.create_index(op.f('ix_source_pages_source_type'), 'source_pages', ['source_type'], unique=False)
    op.create_table('transfer_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('applicant_type', sa.String(length=50), nullable=False),
    sa.Column('sending_institution_type', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('course_level', sa.String(length=100), nullable=True),
    sa.Column('degree_applicability', sa.Text(), nullable=True),
    sa.Column('class_standing_effect', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_record_ids', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('unresolved_fields', sa.JSON(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_transfer_policies_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_policies'))
    )
    op.create_index(op.f('ix_transfer_policies_applicant_type'), 'transfer_policies', ['applicant_type'], unique=False)
    op.create_index(op.f('ix_transfer_policies_confidence_tier'), 'transfer_policies', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_transfer_policies_content_hash'), 'transfer_policies', ['content_hash'], unique=False)
    op.create_index(op.f('ix_transfer_policies_institution_id'), 'transfer_policies', ['institution_id'], unique=False)
    op.create_index(op.f('ix_transfer_policies_policy_type'), 'transfer_policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_transfer_policies_review_status'), 'transfer_policies', ['review_status'], unique=False)
    op.create_index(op.f('ix_transfer_policies_superseded'), 'transfer_policies', ['superseded'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('unresolved_question', sa.Text(), nullable=False),
    sa.Column('recommended_office', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_review_tasks_institution_id_institutions')),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], name=op.f('fk_review_tasks_source_page_id_source_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_tasks'))
    )
    op.create_index(op.f('ix_review_tasks_institution_id'), 'review_tasks', ['institution_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_reason'), 'review_tasks', ['reason'], unique=False)
    op.create_index(op.f('ix_review_tasks_record_id'), 'review_tasks', ['record_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_record_type'), 'review_tasks', ['record_type'], unique=False)
    op.create_index(op.f('ix_review_tasks_severity'), 'review_tasks', ['severity'], unique=False)
    op.create_index(op.f('ix_review_tasks_source_page_id'), 'review_tasks', ['source_page_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=False),
    sa.Column('crawl_job_id', sa.Uuid(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_content_location', sa.Text(), nullable=False),
    sa.Column('raw_content_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_content_hash', sa.String(length=64), nullable=False),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], name=op.f('fk_source_snapshots_crawl_job_id_crawl_jobs')),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], name=op.f('fk_source_snapshots_source_page_id_source_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots')),
    sa.UniqueConstraint('source_page_id', 'raw_content_hash', name=op.f('uq_source_snapshots_source_page_id_raw_content_hash'))
    )
    op.create_index(op.f('ix_source_snapshots_crawl_job_id'), 'source_snapshots', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_source_snapshots_normalized_content_hash'), 'source_snapshots', ['normalized_content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_raw_content_hash'), 'source_snapshots', ['raw_content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_page_id'), 'source_snapshots', ['source_page_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_start', sa.Integer(), nullable=True),
    sa.Column('evidence_end', sa.Integer(), nullable=True),
    sa.Column('css_selector', sa.Text(), nullable=True),
    sa.Column('xpath', sa.Text(), nullable=True),
    sa.Column('table_identifier', sa.Text(), nullable=True),
    sa.Column('row_identifier', sa.Text(), nullable=True),
    sa.Column('heading_context', sa.Text(), nullable=True),
    sa.Column('footnote_context', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catalog_year', sa.String(length=30), nullable=True),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('authority_tier', sa.String(length=50), nullable=False),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('reviewer_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_evidence_records_source_snapshot_id_source_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_records'))
    )
    op.create_index(op.f('ix_evidence_records_source_snapshot_id'), 'evidence_records', ['source_snapshot_id'], unique=False)
    op.create_table('source_change_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('current_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('changed_blocks', sa.JSON(), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_source_change_events_current_snapshot_id_source_snapshots')),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_source_change_events_previous_snapshot_id_source_snapshots')),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], name=op.f('fk_source_change_events_source_page_id_source_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_change_events'))
    )
    op.create_index(op.f('ix_source_change_events_source_page_id'), 'source_change_events', ['source_page_id'], unique=False)
    op.create_table('requirement_expressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('expression', sa.JSON(), nullable=False),
    sa.Column('original_source_text', sa.Text(), nullable=False),
    sa.Column('evidence_record_id', sa.Uuid(), nullable=True),
    sa.Column('parse_confidence', sa.String(length=50), nullable=False),
    sa.Column('unresolved_warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_record_id'], ['evidence_records.id'], name=op.f('fk_requirement_expressions_evidence_record_id_evidence_records')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_requirement_expressions_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_expressions'))
    )
    op.create_index(op.f('ix_requirement_expressions_institution_id'), 'requirement_expressions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_requirement_expressions_node_type'), 'requirement_expressions', ['node_type'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('canonical_code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('credits_min', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('credits_max', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('credit_type', sa.String(length=30), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('prerequisite_expression_id', sa.Uuid(), nullable=True),
    sa.Column('corequisite_expression_id', sa.Uuid(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('repeatability', sa.Text(), nullable=True),
    sa.Column('equivalent_courses', sa.JSON(), nullable=False),
    sa.Column('overlapping_courses', sa.JSON(), nullable=False),
    sa.Column('general_education_designators', sa.JSON(), nullable=False),
    sa.Column('historical_offering_notes', sa.JSON(), nullable=False),
    sa.Column('catalog_version_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_record_ids', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('unresolved_fields', sa.JSON(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name=op.f('fk_courses_catalog_version_id_catalog_versions')),
    sa.ForeignKeyConstraint(['corequisite_expression_id'], ['requirement_expressions.id'], name=op.f('fk_courses_corequisite_expression_id_requirement_expressions')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_courses_institution_id_institutions')),
    sa.ForeignKeyConstraint(['prerequisite_expression_id'], ['requirement_expressions.id'], name=op.f('fk_courses_prerequisite_expression_id_requirement_expressions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('institution_id', 'canonical_code', 'version_number', name=op.f('uq_courses_institution_id_canonical_code_version_number'))
    )
    op.create_index(op.f('ix_courses_campus'), 'courses', ['campus'], unique=False)
    op.create_index(op.f('ix_courses_canonical_code'), 'courses', ['canonical_code'], unique=False)
    op.create_index(op.f('ix_courses_confidence_tier'), 'courses', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_courses_content_hash'), 'courses', ['content_hash'], unique=False)
    op.create_index(op.f('ix_courses_institution_id'), 'courses', ['institution_id'], unique=False)
    op.create_index(op.f('ix_courses_number'), 'courses', ['number'], unique=False)
    op.create_index(op.f('ix_courses_review_status'), 'courses', ['review_status'], unique=False)
    op.create_index(op.f('ix_courses_subject'), 'courses', ['subject'], unique=False)
    op.create_index(op.f('ix_courses_superseded'), 'courses', ['superseded'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('official_name', sa.Text(), nullable=False),
    sa.Column('degree_type', sa.String(length=100), nullable=True),
    sa.Column('college_or_school', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('major_type', sa.String(length=50), nullable=False),
    sa.Column('admission_path', sa.Text(), nullable=True),
    sa.Column('capacity_status', sa.Text(), nullable=True),
    sa.Column('application_required', sa.Boolean(), nullable=True),
    sa.Column('application_terms', sa.JSON(), nullable=False),
    sa.Column('application_deadlines', sa.JSON(), nullable=False),
    sa.Column('minimum_gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('prerequisite_expression_id', sa.Uuid(), nullable=True),
    sa.Column('degree_requirements', sa.JSON(), nullable=False),
    sa.Column('source_scope', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_record_ids', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('unresolved_fields', sa.JSON(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_programs_institution_id_institutions')),
    sa.ForeignKeyConstraint(['prerequisite_expression_id'], ['requirement_expressions.id'], name=op.f('fk_programs_prerequisite_expression_id_requirement_expressions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_index(op.f('ix_programs_campus'), 'programs', ['campus'], unique=False)
    op.create_index(op.f('ix_programs_confidence_tier'), 'programs', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_programs_content_hash'), 'programs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_programs_institution_id'), 'programs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_programs_major_type'), 'programs', ['major_type'], unique=False)
    op.create_index(op.f('ix_programs_official_name'), 'programs', ['official_name'], unique=False)
    op.create_index(op.f('ix_programs_review_status'), 'programs', ['review_status'], unique=False)
    op.create_index(op.f('ix_programs_superseded'), 'programs', ['superseded'], unique=False)
    op.create_table('course_offering_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('offered', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('historical_only', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_offering_observations_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offering_observations')),
    sa.UniqueConstraint('course_id', 'term', 'source_url', name=op.f('uq_course_offering_observations_course_id_term_source_url'))
    )
    op.create_index(op.f('ix_course_offering_observations_course_id'), 'course_offering_observations', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_offering_observations_term'), 'course_offering_observations', ['term'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expression_id', sa.Uuid(), nullable=True),
    sa.Column('minimum_credits', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('minimum_courses', sa.Integer(), nullable=True),
    sa.Column('minimum_grade', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('allowed_courses', sa.JSON(), nullable=False),
    sa.Column('double_counting_rule', sa.Text(), nullable=True),
    sa.Column('residency_rule', sa.Text(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_record_ids', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('unresolved_fields', sa.JSON(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['requirement_expressions.id'], name=op.f('fk_requirements_expression_id_requirement_expressions')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_requirements_institution_id_institutions')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_requirements_program_id_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements'))
    )
    op.create_index(op.f('ix_requirements_confidence_tier'), 'requirements', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_requirements_content_hash'), 'requirements', ['content_hash'], unique=False)
    op.create_index(op.f('ix_requirements_institution_id'), 'requirements', ['institution_id'], unique=False)
    op.create_index(op.f('ix_requirements_program_id'), 'requirements', ['program_id'], unique=False)
    op.create_index(op.f('ix_requirements_requirement_type'), 'requirements', ['requirement_type'], unique=False)
    op.create_index(op.f('ix_requirements_review_status'), 'requirements', ['review_status'], unique=False)
    op.create_index(op.f('ix_requirements_superseded'), 'requirements', ['superseded'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirements_superseded'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_review_status'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_requirement_type'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_program_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_institution_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_content_hash'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_confidence_tier'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_course_offering_observations_term'), table_name='course_offering_observations')
    op.drop_index(op.f('ix_course_offering_observations_course_id'), table_name='course_offering_observations')
    op.drop_table('course_offering_observations')
    op.drop_index(op.f('ix_programs_superseded'), table_name='programs')
    op.drop_index(op.f('ix_programs_review_status'), table_name='programs')
    op.drop_index(op.f('ix_programs_official_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_major_type'), table_name='programs')
    op.drop_index(op.f('ix_programs_institution_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_content_hash'), table_name='programs')
    op.drop_index(op.f('ix_programs_confidence_tier'), table_name='programs')
    op.drop_index(op.f('ix_programs_campus'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_courses_superseded'), table_name='courses')
    op.drop_index(op.f('ix_courses_subject'), table_name='courses')
    op.drop_index(op.f('ix_courses_review_status'), table_name='courses')
    op.drop_index(op.f('ix_courses_number'), table_name='courses')
    op.drop_index(op.f('ix_courses_institution_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_content_hash'), table_name='courses')
    op.drop_index(op.f('ix_courses_confidence_tier'), table_name='courses')
    op.drop_index(op.f('ix_courses_canonical_code'), table_name='courses')
    op.drop_index(op.f('ix_courses_campus'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_requirement_expressions_node_type'), table_name='requirement_expressions')
    op.drop_index(op.f('ix_requirement_expressions_institution_id'), table_name='requirement_expressions')
    op.drop_table('requirement_expressions')
    op.drop_index(op.f('ix_source_change_events_source_page_id'), table_name='source_change_events')
    op.drop_table('source_change_events')
    op.drop_index(op.f('ix_evidence_records_source_snapshot_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_source_snapshots_source_page_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_raw_content_hash'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_normalized_content_hash'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_crawl_job_id'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_source_page_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_severity'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_record_type'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_record_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_reason'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_institution_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_transfer_policies_superseded'), table_name='transfer_policies')
    op.drop_index(op.f('ix_transfer_policies_review_status'), table_name='transfer_policies')
    op.drop_index(op.f('ix_transfer_policies_policy_type'), table_name='transfer_policies')
    op.drop_index(op.f('ix_transfer_policies_institution_id'), table_name='transfer_policies')
    op.drop_index(op.f('ix_transfer_policies_content_hash'), table_name='transfer_policies')
    op.drop_index(op.f('ix_transfer_policies_confidence_tier'), table_name='transfer_policies')
    op.drop_index(op.f('ix_transfer_policies_applicant_type'), table_name='transfer_policies')
    op.drop_table('transfer_policies')
    op.drop_index(op.f('ix_source_pages_source_type'), table_name='source_pages')
    op.drop_index(op.f('ix_source_pages_policy_family'), table_name='source_pages')
    op.drop_index(op.f('ix_source_pages_institution_id'), table_name='source_pages')
    op.drop_index(op.f('ix_source_pages_campus'), table_name='source_pages')
    op.drop_table('source_pages')
    op.drop_index(op.f('ix_exam_credit_rules_superseded'), table_name='exam_credit_rules')
    op.drop_index(op.f('ix_exam_credit_rules_review_status'), table_name='exam_credit_rules')
    op.drop_index(op.f('ix_exam_credit_rules_institution_id'), table_name='exam_credit_rules')
    op.drop_index(op.f('ix_exam_credit_rules_exam_type'), table_name='exam_credit_rules')
    op.drop_index(op.f('ix_exam_credit_rules_exam_name'), table_name='exam_credit_rules')
    op.drop_index(op.f('ix_exam_credit_rules_content_hash'), table_name='exam_credit_rules')
    op.drop_index(op.f('ix_exam_credit_rules_confidence_tier'), table_name='exam_credit_rules')
    op.drop_table('exam_credit_rules')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_institution_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_conflict_records_status'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_record_type'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_institution_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_conflict_type'), table_name='conflict_records')
    op.drop_table('conflict_records')
    op.drop_index(op.f('ix_catalog_versions_superseded'), table_name='catalog_versions')
    op.drop_index(op.f('ix_catalog_versions_institution_id'), table_name='catalog_versions')
    op.drop_table('catalog_versions')
    op.drop_index(op.f('ix_admissions_rules_superseded'), table_name='admissions_rules')
    op.drop_index(op.f('ix_admissions_rules_rule_type'), table_name='admissions_rules')
    op.drop_index(op.f('ix_admissions_rules_review_status'), table_name='admissions_rules')
    op.drop_index(op.f('ix_admissions_rules_institution_id'), table_name='admissions_rules')
    op.drop_index(op.f('ix_admissions_rules_content_hash'), table_name='admissions_rules')
    op.drop_index(op.f('ix_admissions_rules_confidence_tier'), table_name='admissions_rules')
    op.drop_index(op.f('ix_admissions_rules_campus'), table_name='admissions_rules')
    op.drop_index(op.f('ix_admissions_rules_applicant_type'), table_name='admissions_rules')
    op.drop_table('admissions_rules')
    op.drop_index(op.f('ix_record_versions_superseded'), table_name='record_versions')
    op.drop_index(op.f('ix_record_versions_record_type'), table_name='record_versions')
    op.drop_index(op.f('ix_record_versions_content_hash'), table_name='record_versions')
    op.drop_index(op.f('ix_record_versions_canonical_key'), table_name='record_versions')
    op.drop_table('record_versions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
